'use client'

import { useState } from 'react'
import Section from '../components/common/Section'
import { ChevronRight, ChevronDown } from 'lucide-react'

interface NoteSection {
  id: string
  title: string
  content: string[]
}

const noteSections: NoteSection[] = [
  {
    id: 'executive',
    title: '1. Executive Summary',
    content: [
      'Parksense is a dual-purpose urban intelligence platform:',
      '• For Drivers: A real-time parking finder, payment wallet, and "Smart Commuter" tool.',
      '• For Property: A weather station network and asset management system for skyscrapers.',
      'The system utilizes a Freemium consumer model while unlocking B2B revenue through building management and environmental data sales.',
    ],
  },
  {
    id: 'roadmap',
    title: '2. Project Roadmap (Phased Delivery)',
    content: [
      'Phase 1: The "Connected Asphalt" MVP (Months 1-2)',
      '• Deploy Test Site: 1 Gateway + 5 Parking Sensors + 1 Weather Station',
      '• Backend: LORIOT NS → Webhook → /api/iot/uplink → Kafka → consumers → Tiger Cloud (Timescale)',
      '• App (Alpha): Live Map showing Green/Red dots',
      '• Feature: "Manual Pin" Car Finder (Level A)',
      '',
      'Phase 2: The "Dubai Driver" Update (Months 3-4)',
      '• Unified Payments: Aggregation of RTA (Dubai), Mawaqif (Abu Dhabi), and Sharjah payments',
      '• "Summer Mode": Routing algorithm prioritizing covered/shaded parking',
      '• Car Finder Level B: Implement "Smart Handshake" logic',
      '• App (Beta): Release to TestFlight',
      '',
      'Phase 3: Monetization & Intelligence (Months 5-6)',
      '• Weather Layer: Frontend toggle for Heatmaps & Air Quality overlays',
      '• Subscription Gate: Stripe/Apple Pay integration for "Pro" upgrades',
      '• Alerts Engine: Push notifications (e.g., Sandstorm Warnings)',
      '• Merchant Validation: QR Code scanning logic for retail partners',
      '',
      'Phase 4: Skyscrapers & Ecosystem (Month 7+)',
      '• "Spot Guard": Security alerts for private residential bays',
      '• "Spot Share": Airbnb-style subletting of private parking spots',
      '• 3rd Party Integration: CAFU (Fuel) and Car Wash API connections',
    ],
  },
  {
    id: 'techstack',
    title: '3. Tech Stack ("Bleeding Edge" 2025 Architecture)',
    content: [
      '3.1. Mobile App (Performance First)',
      '• Framework: Expo SDK 52+ (React Native)',
      '• Routing: Expo Router (file-based routing)',
      '• Graphics: React Native Skia (High-performance UI for weather overlays)',
      '• Maps: Mapbox (mobile SDK) or Google Maps SDK (routing + traffic)',
      '• Driving UX: CarPlay first (UAE reality), then in-app map as secondary',
      '',
      '3.2. Backend & API (Vercel + Services + Event Bus)',
      '• Portal/Web: Next.js hosted on Vercel',
      '• Backend: NestJS (TypeScript) services for IoT, routing, payments, ads, analytics',
      '• LoRaWAN NS: LORIOT (enterprise/private)',
      '• Ingestion: LORIOT Webhook → /api/iot/uplink (store raw + decoded payloads)',
      '• Event bus: Kafka (managed) for scalable ingestion + replay + decoupled processing',
      '• Database: ✅ Tiger Cloud (Timescale) — managed PostgreSQL with TimescaleDB + vector support (LIVE / PROD)',
      '• Time-series: TimescaleDB hypertables (sensor logs, events, analytics)',
      '• AI: pgvector extension (future pattern matching / personalization)',
    ],
  },
  {
    id: 'enterprise-stack',
    title: '3.3. Enterprise Day-1 Reference Architecture (Recommended Default)',
    content: [
      'Recommended “enterprise day 1” combo (practical)',
      'If you want a single coherent default:',
      '• LORIOT (enterprise/private) as NS',
      '• Backend: NestJS + Postgres + Timescale',
      '• Event bus: Kafka (managed)',
      '• Infra: AWS (or GCP) with proper networking, WAF, IAM, monitoring',
      '• Portal: Next.js',
      '',
      'Enterprise data flow (sensor → iPhone app):',
      '1) Sensor sends LoRaWAN uplink (occupancy/weather).',
      '2) Gateway receives RF and forwards packets over IP backhaul.',
      '3) LORIOT NS authenticates + decrypts + deduplicates + attaches metadata (RSSI/SNR/gateway/time).',
      '4) LORIOT Integration forwards event to Backend Ingest (HTTP webhook).',
      '5) NestJS validates + normalizes + assigns internal IDs (tenant/site/sensor).',
      '6) NestJS publishes to Kafka topics (raw uplinks + normalized sensor events).',
      '7) Kafka consumers decode payloads, run rules/alerts, compute current state.',
      '8) Write storage:',
      '   • Postgres: users/orgs/sensors/current state/config',
      '   • TimescaleDB: time-series sensor logs/events for analytics',
      '9) NestJS API serves both:',
      '   • Commercial iPhone app (map, availability, history)',
      '   • Portal (Next.js) dashboards + ops tools',
      '10) Realtime (optional): WebSockets/SSE + push notifications for alerts.',
      '',
      'Effort estimate (solo developer + AI, single-tenant MVP):',
      '• MVP Pilot (payments + subscriptions + occupancy + weather): ~7–10 weeks full-time',
      '• Enterprise-ready v1 (multi-site + hardening + ops): ~3–4 months total from start',
      '',
      'What “multiple operators” means (multi-tenant):',
      '• An operator is a separate organization that manages its own parking assets and needs its own portal + data.',
      '• Examples: municipality authority, mall operator, property/tower management company, or a private parking operator.',
      '• Multi-tenant requirement: strict separation so Operator A cannot see Operator B sensors, events, dashboards, or billing.',
    ],
  },
  {
    id: 'hardware',
    title: '4. Hardware Architecture',
    content: [
      '4.1. Parking Sensors (Occupancy)',
      '• Device: MokoSmart LW009 (LoRaWAN)',
      '• Mounting: Surface-mounted (Asphalt/Concrete)',
      '• Trigger: Magnetic/Radar event (Car Enters/Leaves)',
      '',
      '4.2. Weather Stations (Environmental)',
      '• Device: Seeed Studio SenseCAP ONE S900 (or Rika RK900)',
      '• Metrics: PM2.5, PM10, Temp, Humidity, Wind Speed, Rain',
      '• Bridge: RAK7431 (RS485 to LoRa Bridge)',
      '• Logic: Weather station is wired to RAK7431 on the gateway pole; transmits wirelessly to the network',
      '',
      '4.3. Tower Connectivity (Vertical Scale)',
      '• Infrastructure: 1 Gateway on Podium/Ground + LoRa Repeaters every 3-4 floors to ensure signal reaches B3 basements and P10 podiums',
    ],
  },
  {
    id: 'modules',
    title: '5. Functional Modules',
    content: [
      '5.1. Smart Car Finder & Wayfinding (3 Levels)',
      '• Level A (Manual): User taps "Park Here" on map',
      '• Level B (Smart Handshake): Backend auto-pins location when sensor status = Occupied AND user GPS = <15m from Sensor AND phone activity = Driving → Walking',
      '• Level C (Offline): User snaps photo of pillar; image saved locally (No Internet required)',
      '',
      '5.2. Hyper-Local Weather Intelligence',
      '• Visuals: Map toggles for "Heatmap" (Real-feel temp) and "Air Quality" (PM2.5)',
      '• Car Wash Rule: If Rain Probability > 50% in next 4 hours → Disable "Order Wash" button',
      '• Health Rule: If PM2.5 > High → Suggest "Indoor Parking" for walking routes',
      '',
      '5.3. "Tower Mode" (Skyscraper Management)',
      '• Spot Guard: Resident sets status to "Away". If sensor detects car, alert sent',
      '• Spot Share: Resident lists spot availability (e.g., 09:00-18:00). Visitors book and pay via app',
      '• Guest Pass: QR code for visitors guides them to specific "Green" visitor bays only',
      '',
      '5.4. Unified Payments',
      '• Geo-Fencing: Auto-detects zone (Dubai Zone A vs. Abu Dhabi)',
      '• One-Tap Pay: Aggregates SMS/API gateways for RTA, Mawaqif, and Private barriers',
    ],
  },
  {
    id: 'business',
    title: '6. Business Model (Tiers)',
    content: [
      'Free Tier ("The Daily Driver")',
      '• Real-Time Green/Red Map',
      '• Unified Payment Gateway',
      '• Manual Car Finder',
      '• Basic Navigation',
      '',
      'Pro Tier (~29 AED/Month)',
      '• Summer Mode: Routing to shaded/basement spots',
      '• Smart Handshake: Auto-car pinning',
      '• Weather Intelligence: Full Air Quality/Heat maps',
      '• Smart Alerts: Sandstorm/Rain warnings',
      '• Discounts: 10-15% off Valet & Car Wash',
    ],
  },
  {
    id: 'userstories',
    title: '7. User Stories',
    content: [
      'US-01: The One-Tap Payment',
      'As a Daily Commuter, I want to pay for parking in any RTA or Mawaqif zone instantly so that I don\'t have to remember different zone codes.',
      '',
      'US-02: Summer Mode (Heat Avoidance)',
      'As an Executive with a leather-interior car, I want to be routed to covered parking during the afternoon so that my car doesn\'t get dangerously hot.',
      '',
      'US-03: Smart Handshake (Car Finder)',
      'As a Shopper at Dubai Mall, I want to have my parking spot automatically saved when I walk away.',
      '',
      'US-04: The Spot Guard (Security)',
      'As a JLT Resident, I want to receive an alert if my private parking spot is occupied while I am away.',
      '',
      'US-05: The Spot Share (Monetization)',
      'As a Landlord in Marina, I want to list my empty parking spot for rent during working hours.',
      '',
      'US-06: Weather-Aware Services',
      'As a Car Owner, I want to be warned if I try to order a car wash when rain is predicted.',
      '',
      'US-07: Offline Photo Log',
      'As a Tourist in a deep basement (No Signal), I want to take a photo of the parking pillar number inside the app.',
      '',
      'US-08: Health & Air Quality',
      'As an Asthmatic user, I want to see the real-time air quality (PM2.5) of a neighborhood on the map.',
      '',
      'US-09: EV Charging Availability',
      'As an EV Owner, I want to see the real-time availability of charging stations.',
      '',
      'US-10: Seamless Visitor Access',
      'As a Guest visiting a residential tower, I want to scan a digital pass at the barrier.',
    ],
  },
  {
    id: 'technical',
    title: '8. Technical Requirements (Backend)',
    content: [
      '8.1. Database Schema (Tiger Cloud / PostgreSQL + TimescaleDB)',
      '• users: standard auth profile + roles',
      '• sites/zones/bays: map configuration and hierarchy',
      '• sensors: id, devEUI, lat, long, type (parking/weather), zone_id, status, last_seen, battery',
      '• sensor_events (Timescale hypertable): time, sensor_id, decoded_json, raw_payload, rssi/snr, gateway_id',
      '• parking_sessions: user_id, bay_id/sensor_id, start_time, end_time, payment_state, proof (optional)',
      '',
      '8.2. Payload Decoders',
      '• Parking (MokoSmart): Decode Hex to { status: boolean, battery: int }',
      '• Weather (RAK7431): Decode Modbus Register array to { temp: float, humidity: float, wind_speed: float, rain: boolean }',
      '',
      '8.3. Realtime',
      '• Publish state changes via WebSockets/SSE (app + portal) and push notifications for alerts',
      '• Optional: use Kafka topics as the internal event backbone for realtime fan-out',
    ],
  },
  {
    id: 'parksense-functional',
    title: '9. ParkSense App Functionality (Sensor-First Competitive Moat)',
    content: [
      'Key insight: competitors estimate occupancy from payments per zone. ParkSense uses per-bay sensors → “We don’t guess. We see.”',
      '',
      '9.1. Core App Screens (MVP)',
      '• Home (Map-first): live parking availability + “Navigate to best spot”',
      '• Search/Destination: address/POI search → choose destination',
      '• Results: ranked parking options near destination (free first, then paid)',
      '• Parking Result: selected bay/cluster with drive ETA + walk ETA + confidence',
      '• Navigation View: simplified last-300m UI (safe driving)',
      '• Parked: car finder (auto + manual) + timer + pay/extend actions',
      '• Wallet/Payments: parking payments + subscriptions + receipts',
      '• Profile: account, vehicles (optional), preferences, privacy',
      '',
      '9.2. Map & Availability UX (Bay-level where sensors exist)',
      '• Bay colors: Green = free, Red = occupied, Gray = unknown/unreliable',
      '• Each bay shows: last update + confidence score',
      '• Filters: closest, cheapest, shaded/covered (“Summer Mode”), EV, accessible, height limit',
      '• Fallback hierarchy: Bay → Cluster → Zone (still useful with partial sensor coverage)',
      '',
      'Destination-first ranking logic (key UX):',
      '• User sets destination pin → app prioritizes Free parking bays closest to destination first',
      '• After free options: show Paid parking options (RTA/operator) as the next tier',
      '• Provide a clear toggle/segment: Free | Paid | All (so users trust the ranking)',
      '',
      '9.3. Best-Spot Routing (the WOW feature)',
      '• “Navigate to best spot” routes to a specific bay (or best cluster) near destination',
      '• Re-route instantly if the chosen bay becomes occupied while the user is approaching',
      '• “Will it still be free when I arrive?” uses: live sensor trends + historical patterns',
      '',
      '9.3.1. Glance Surfaces (Supported, High-Impact Driving UX)',
      'CarPlay-first strategy (UAE reality): most drivers use CarPlay for navigation; treat CarPlay as the primary driving UI.',
      '• CarPlay (priority #1): show a simplified “Best Spot” card + occupancy confidence + re-route prompts while driving',
      '• Android Auto (priority #2): same concepts for Android drivers',
      '• Widgets: “Nearby Free Spots” + “Best Spot to Destination” quick actions from Home Screen',
      '• Live Activities (iOS): lock-screen / dynamic island updates for: driving → parking → payment timer → extend reminders',
      '• In-app map (secondary): planning, exploration, walking guidance, payments, and detailed bay-level view when parked',
      '• Bikers/phone navigation: support in-app navigation as a fallback when CarPlay is not available',
      '',
      '9.4. Payments & Reservations (MVP + Enterprise)',
      'MVP (fast, compliant): Assisted payment',
      '• Detect zone via geofence + bay location',
      '• Prepare correct payment payload (duration/zone) and launch official flow (deep link / SMS compose)',
      '• ParkSense tracks timer, reminders, and “extend now” prompts',
      '',
      'Enterprise (best): Direct payment session (via partner/operator APIs)',
      '• Start/extend/stop sessions inside ParkSense',
      '• Optional auto-extend rules (user-controlled)',
      '',
      'Reservations:',
      '• Private inventory first (malls/towers) where VisionDrive controls access + sensors',
      '• Public inventory later (requires operator integration/permission)',
      '',
      '9.5. Car Finder (Level A/B/C)',
      '• Level A: manual “Park here” pin',
      '• Level B: smart handshake (sensor occupied + phone nearby + motion shift driving→walking) auto-saves bay',
      '• Level C: offline photo log (pillar/floor) for deep basements',
      '',
      '9.6. Weather / Comfort Intelligence',
      '• Map overlay: heat/shade + air quality (where sensors exist)',
      '• Summer Mode routing: prefer shaded/covered parking and cooler walking routes',
      '',
      '9.7. Operator Portal (must-have for enterprise sales)',
      '• Sensor fleet health: uptime, last seen, battery, false-positive detection',
      '• Live occupancy dashboard + heatmaps + exports',
      '• Audit logs + role-based access',
      '',
      '9.7.1. Business Ads / Sponsored Map Pins (B2B revenue)',
      '• Businesses can pay ParkSense to appear on the map (sponsored pins) near relevant destinations/parking areas',
      '• Pricing model (MVP): pay-per-action (tap/call/directions) or pay-per-redemption (QR/offer)',
      '• Rules to protect UX: ads never override “best spot” routing; they appear as a separate “Sponsored” layer',
      '• Portal: self-serve ad campaign creation, geo-radius targeting, budget caps, analytics dashboard',
      '',
      '9.8. Monetization (subscription)',
      '• Free: zone-level + limited bay-level, basic navigation, manual car finder',
      '• Pro: bay-level “high confidence mode”, Summer Mode, smart handshake, alerts, weather overlays',
      '',
      '9.9. Technical Requirements (Refined Spec)',
      'Goal: real-time per-bay truth + best-spot routing + payments + monetization (ads + subscription).',
      '',
      '9.9.1. Core Parking Management & Visualization',
      '• Real-time occupancy UI: display individual bays on map (where sensors exist)',
      '• Color coding: Green (Available) / Red (Occupied) / Gray (Unknown or low-confidence)',
      '• Confidence model: show last update + confidence score; hide/deprioritize unhealthy sensors',
      '• EV charging: dedicated bay markers and real-time availability (via API, where possible)',
      '• Free parking zones: digital mapping of non-paid/public areas; integrate sensors to show true availability',
      '• Paid parking zones: RTA/operator zones with tariffs (per hour / per zone) visible pre-arrival',
      '',
      '9.9.2. Navigation & Smart Routing',
      '• Destination-first UX: user drops destination → app ranks Free options first (closest), then Paid options',
      '• Best-spot routing: navigate to a specific bay/cluster when possible (fallback to zone entrance/centroid)',
      '• “Metro-style / last-mile” guidance: simplified linear UI for last 300–800m into parking area',
      '• Instant re-route: if target bay flips to occupied while approaching → auto-switch to next best bay',
      '• Recommendation engine inputs: proximity, cost (free vs paid), confidence, shade/covered, EV/accessibility',
      '• Glance-first driving UX: CarPlay first, then Android Auto; iOS Live Activities for safe, low-distraction updates',
      '',
      '9.9.3. Booking, Payments & Validation',
      'Reservations:',
      '• Private inventory first (malls/towers/paid lots we control) → reserve a bay in advance',
      '• Public inventory later (requires operator integration/permission)',
      '',
      'Payments:',
      '• MVP (fast): assisted payment for RTA/operator (zone detect + deep link/SMS compose + timer + extend prompts)',
      '• Enterprise: direct payment session via partner APIs (start/extend/stop inside ParkSense)',
      '• Methods: Apple Pay / Google Pay / credit card for subscriptions + private reservation payments',
      '',
      'Parking validation (“Spend X get free parking”):',
      '• Merchant list on map + in destination screen (participating cafes/shops)',
      '• Validation mechanism: QR scanning (MVP) → POS/API integration later',
      '• Rules engine applies discount/free-time to the parking session',
      '',
      '9.9.4. Predictive Analytics & AI (after baseline truth works)',
      '• Occupancy forecasting per zone/cluster/bay using historical sensor data',
      '• User warnings: “High occupancy expected at 18:00” + best time windows',
      '• Visuals: peak-hour graphs and reliability/confidence charts for operators',
      '',
      '9.9.5. Third-Party O2O Services (partner monetization)',
      '• Car wash to parked location (partner API) + “disable if rain soon” logic',
      '• Fuel delivery (CAFU-like) to parked location (partner API)',
      '• Hyper-local recommendations: geo-fenced “what’s nearby” cards after parking',
      '',
      '9.9.6. Ads Platform (LBS monetization)',
      '• Sponsored pins/ads on map (separate Sponsored layer; never overrides best-spot routing)',
      '• Pricing: pay-per-action (tap/call/directions) or pay-per-redemption (QR/offer)',
      '• Portal tooling: campaign creation, geo-radius targeting, budget caps, analytics',
      '',
      '9.9.7. Premium Hardware Add-on (Vehicle Tracking)',
      '• Optional OBDII/GPS tracker subscription for car location tracking',
      '• Vehicle map view + trip logs + parking history (“personal cabinet” in portal/app)',
    ],
  },
  {
    id: 'portal-features',
    title: '10. Operator Portal (Backend) — Features to Build First (Gateway Not Required)',
    content: [
      'Goal: deliver an enterprise-grade operator console that proves sensor-first accuracy, even before gateways arrive (use simulated/replayed uplinks).',
      '',
      '10.0. Access Model (Master ADMIN vs Customer / Building Manager)',
      'We will sell the portal to customers (building managers / parking operators). They must only see their own parking lots, while VisionDrive ADMIN sees everything.',
      '• Tenant concept: each customer = tenant (building/operator). Every entity must be scoped by tenant_id (and site_id).',
      '• Master ADMIN (VisionDrive): full cross-tenant view + can onboard/disable customers and see global analytics.',
      '• Customer ADMIN (Building Manager): manages only their tenant’s sites/zones/bays/sensors, users, and settings.',
      '• Customer OPS: day-to-day operations (health, events, overrides) within their tenant only.',
      '• Customer ANALYST: read-only dashboards/reports within their tenant only.',
      '• Data isolation rule: ALL queries must enforce tenant_id (server-side), never rely on the UI to hide data.',
      '',
      '10.1. Core Portal Modules (MVP)',
      '• Dashboard: total bays, occupied %, free bays, sensor health, last 15 min events',
      '• Live Map: sites/zones/bays with real-time colors + last update + confidence',
      '• Fleet Health: sensors list, last_seen, battery, RSSI/SNR, downtime alerts',
      '• Events Viewer: raw uplinks + decoded JSON + validation status + replay tools',
      '• Reports: occupancy by hour/day, peak times, zone heatmaps, exports (CSV)',
      '',
      '10.2. Digital Twin / Inventory (must-have for selling to enterprises)',
      '• Sites: site address, geofence polygon, timezone, operator settings',
      '• Zones: paid/free, tariff metadata, entrances, policy rules, capacity',
      '• Bays: bay geometry/marker, attributes (EV, accessible, shaded, height)',
      '• Sensors: devEUI, model, firmware, install date, bay binding, status',
      '• Assets: gateways (later), vehicles (optional premium), merchants/partners',
      '',
      '10.3. Sensor Truth & Confidence (the “moat” in the portal)',
      '• Confidence score per bay/sensor: freshness + health + stability',
      '• Auto-degrade unhealthy sensors → show Gray (unknown) instead of lying',
      '• False-positive tooling: mark incidents + retrain rules thresholds (manual first)',
      '• “Ground truth correction” workflow (operator can override bay state temporarily)',
      '',
      '10.4. Simulated / Replayed IoT Data (until gateway arrives)',
      '• File upload: accept JSON/CSV “uplink log” and ingest as sensor_events',
      '• Replay engine: choose time range + playback speed (1x/10x/100x) → publishes realtime updates',
      '• Data generator: create synthetic occupancy patterns per zone (rush hour / mall weekend)',
      '• Decoder test bench: paste payload → decode → preview DB event → save',
      '• Validation: reject malformed events, keep a dead-letter view for debugging',
      '',
      '10.5. Alerts & Rules Engine (operator-grade operations)',
      '• Alert types: low battery, offline sensor, flapping sensor, suspicious occupancy',
      '• Business rules: reserve/private bays, time windows, enforcement integrations (later)',
      '• Notification targets: email/Slack/webhook (MVP) + push (later)',
      '',
      '10.6. Analytics (MVP → Enterprise)',
      '• Occupancy trends: by site/zone/bay (hour/day/week), seasonality, events correlation (weather)',
      '• Utilization KPIs: turnover, average dwell time, vacancy rate, anomaly detection',
      '• Forecasting: later — only after confidence + baseline data are stable',
      '',
      '10.7. Integrations (prepare now, connect later)',
      '• LoRaWAN NS: LORIOT/ChirpStack webhooks → /api/iot/uplink (later)',
      '• Payments: Stripe for subscriptions + receipts; operator APIs for sessions (later)',
      '• Maps: Mapbox styles + overlays; export GeoJSON/KML for stakeholders',
      '',
      '10.8. Security, RBAC, Audit (enterprise requirement)',
      '• Roles: MASTER_ADMIN (VisionDrive), CUSTOMER_ADMIN, CUSTOMER_OPS, CUSTOMER_ANALYST (MVP) + granular permissions later',
      '• Tenant scoping: customer users are always bound to tenant_id; Master Admin can switch tenant context',
      '• Audit log: who changed what (bays/sensors/rules), with timestamps and IP',
      '• Multi-tenant ready: keep tenant_id on every entity even if single-tenant at first (prevents rewrites later)',
      '',
      '10.9. Portal Pages (concrete build list)',
      '• /portal (dashboard)',
      '• /portal/sites (CRUD) → /portal/sites/[id]',
      '• /portal/zones (CRUD) → /portal/zones/[id]',
      '• /portal/bays (CRUD) → /portal/bays/[id] (history + overrides)',
      '• /portal/sensors (CRUD) → /portal/sensors/[id] (health + events)',
      '• /portal/events (timeseries viewer + filters + export)',
      '• /portal/replay (upload + replay controls + decoder bench)',
      '• /portal/reports (charts + CSV export)',
      '• /portal/admin (users/roles/settings/audit)',
      '• /portal/admin/tenants (Master Admin only: customers/buildings/operator accounts)',
      '',
      '10.10. Customer Portal UI Blueprint (reference mock)',
      'Reference mock: Parkzone Dashboard (Dribbble) — use this as the customer/operator UI style direction.',
      '• Layout: left sidebar navigation + top search/filter bar + main dashboard canvas',
      '• Dashboard hero area: “Parking occupancy” overview with KPI cards (Total spots, Available, Occupied, Occupancy %)',
      '• Trends: occupancy chart (day/week/month) + peak time callouts',
      '• Map-first panel: parking-lot map with bay markers (Green/Red/Gray) + zone selector',
      '• Operational widgets: Alerts/Incidents feed, Sensor health list (offline/low battery), Recent events table',
      '• Drilldowns: click zone → click bay → bay details (history, last-seen, overrides, notes)',
      '• Consistency rules: every widget must be tenant-scoped for customers; Master Admin can switch tenant context',
      '',
      '10.11. Master Admin UI Blueprint (global view + drilldown)',
      'Reference mock: Vehicle Tracking Management Dashboard (Dribbble) — use this as the Master Admin “fleet ops” style direction.',
      'Master Admin goal: one screen shows the entire company picture (all customers), and one click drills into a specific customer/site with the SAME UI the customer sees.',
      '• Global map: all sites plotted (clustered) with status badges; filter by tenant, city, site, health',
      '• Global KPIs: total tenants, total sites, total sensors, online %, offline %, low-battery %, events/min',
      '• Availability & downtime: SLA uptime (7/30/90 days), MTTR, downtime incidents list, “top failing sites/sensors”',
      '• Equipment inventory: gateways (later), sensors by model/firmware, last firmware seen, install age',
      '• Ops queues: offline sensors, flapping sensors, low battery, decoder errors, replay failures (dead-letter)',
      '• Drilldown (critical): Tenant → Site → Zone → Bay → Sensor (history, events, overrides, maintenance notes)',
      '• Enhanced controls: impersonate/assume-tenant-view (read-only), push config/decoder version (later), maintenance tickets',
      '• Data access: Master Admin sees cross-tenant aggregates; customer data remains isolated for customer accounts',
      '',
      '10.12. Analytics & Stats UI (hardware-first reporting)',
      'Reference mock: Airport Ops / Airport management Dashboard (Dribbble) — use this as the reporting/analytics layout direction.',
      'We must have statistics and reports for ALL hardware and ops workflows (this is a sales requirement).',
      '• Fleet uptime: online/offline rates by tenant/site/model, SLA compliance, MTBF/MTTR',
      '• Battery analytics: low-battery forecast, battery drain rate, replacement schedule',
      '• Connectivity quality: RSSI/SNR distributions, packet loss estimates, “bad coverage” zones',
      '• Firmware & config drift: versions by model/site, outliers, upgrade planning (later)',
      '• Event throughput: uplinks/min, decode errors, dead-letter volume, replay success rate',
      '• Occupancy analytics: utilization, turnover, dwell time, peak hour heatmaps (per site/zone)',
      '• Exports: CSV for management, scheduled email reports (weekly/monthly), shareable links (later)',
      '',
      '10.13. Hardware Health Module (Sensors + Gateways) + Alerts System',
      'Reference mock: Location Generator / Smart Geo-Targeting Tool Dashboard (Dribbble) — use this as the hardware module layout direction (map + device tables + status cards).',
      'Hardware goal: operators must instantly see what is healthy vs failing, and we must plan maintenance (rotation/replacements) before service quality drops.',
      '',
      '10.13.1. Sensor Performance Reports (operator-facing)',
      'Reference mock: Real estate dashboard “agent performance reports” (Dribbble) — use this as the sensors performance reporting UI structure (scorecards + rankings + trends + period comparison).',
      'Report goal: a manager can answer “Which sensors/sites are getting worse, why, and what do we replace first?” in under 60 seconds.',
      '• Report dimensions: Tenant → Site → Zone → Sensor model → Individual sensor',
      '• Time controls: last 24h / 7d / 30d / custom + compare vs previous period',
      '• Health score (0–100) per sensor: weighted blend of uptime, battery, signal quality, data consistency',
      '• Uptime & downtime: % uptime, offline incidents count, longest outage, MTTR',
      '• Signal strength: RSSI/SNR median + p10/p90, degradation trend, “coverage suspect” flag',
      '• Battery: current %, drain/day, forecast “days to replace”, battery anomalies',
      '• Data quality: decode errors, missing fields, out-of-range values, duplicate bursts',
      '• Stability: flapping rate (state changes/hour), noise score, “unreliable sensor” flag',
      '• Output: Top 10 best/worst sensors, “replace/inspect” recommended list, CSV export',
      '',
      'Sensors (per tenant/site/zone):',
      '• Days in use: install_date → “days active” + replacement/rotation policy (e.g., battery/service interval)',
      '• Uptime/downtime: last_seen freshness + incident timeline; SLA view (7/30/90 days)',
      '• Signal strength: RSSI/SNR trends, worst sensors list, “coverage issues” by zone',
      '• Battery: current battery %, drain rate, “replace within X days” forecast',
      '• Flapping detection: too many state changes in short time → flag as unreliable',
      '',
      'Gateways (as soon as gateways arrive; portal-ready day-1):',
      '• Inventory: model, serial, firmware, site binding, install date, status',
      '• Health: online/offline, last heartbeat, backhaul (LTE/WiFi/Ethernet), packet forwarder status',
      '• Coverage: sensors heard per gateway, RSSI/SNR heat, “gateway blind spots”',
      '',
      '10.13.2. LoRaWAN Gateways (Units) — Overview Report',
      'Reference mock: Location Generator / Smart Geo-Targeting Tool Dashboard (Dribbble) — reuse for “units overview” (map + status cards + device list).',
      'Report goal: quickly answer “Which gateways are down, which sites are impacted, and what coverage is degrading?”',
      '• KPI cards: gateways online/offline, sites impacted, sensors affected, alerts open, events/min',
      '• Map: gateways pinned to locations with status ring (green/yellow/red) + cluster view',
      '• Units table: model, firmware, backhaul, last heartbeat, uptime (7/30/90), sensors heard (24h), incidents',
      '• Coverage panel: sensors-per-gateway distribution, “weak coverage” zones, blind-spot suggestions (add gateway / move antenna)',
      '• Drilldown: gateway → heard sensors list → per-sensor link quality (RSSI/SNR trend) + incident history',
      '',
      '10.13.3. Network Overview (full LoRaWAN visibility: nodes + links + locations)',
      'Reference mock: Sentinel — Network Graph View Analytics (Dribbble) — use this as the network graph visualization direction.',
      'View goal: full network visibility with hardware pinned to locations, like “nodes” and “edges” that explain coverage + failures.',
      '• Dual view: Map (geo) + Graph (topology). Selecting a node highlights it in both views.',
      '• Nodes: gateways, sensors, (later) network server, ingestion endpoints, processing workers',
      '• Edges: uplink paths (sensor → gateway), quality overlay (RSSI/SNR, last_seen, packet loss estimate)',
      '• Time slider: “show topology/health at time T” + “replay last 24h incidents”',
      '• Health overlays: offline clusters, high-error edges, decode error hotspots, dead-letter spikes',
      '• Ops actions: open incident, assign technician, add maintenance note, export affected device list',
      '• Multi-tenant: Customer users see only their tenant graph; Master Admin can switch tenant or view global aggregates',
      '',
      '10.13.4. Weather Equipment Dashboard (multi-location environmental monitoring)',
      'Reference mock: HailTrace — Main Dashboard (Dribbble) — use this as the weather/environment monitoring UI direction (map + cards + trends).',
      'Weather goal: a city/building operator can see real-time environmental conditions per location and spot anomalies (storms, dust, poor air quality).',
      '• Map-first view: weather stations pinned to locations with color overlays (temp/PM2.5/humidity/wind) + clustering',
      '• Station cards: temperature, humidity, wind speed/gust, rain flag, AQI/PM2.5/PM10 (if available), last update',
      '• Trends: last 1h/24h/7d charts per metric + compare across locations',
      '• Alerts: threshold-based (AQI high, wind high, rain detected, sensor offline, out-of-range values)',
      '• Health: battery/uptime/signal quality + “bad data” detection (stuck values, spikes)',
      '• Exports: CSV per station/site + scheduled daily summary report (email)',
      '',
      'Alerts system (must-have):',
      '• Alert types: sensor offline, gateway offline, low battery, poor signal, flapping, decode errors, dead-letter spikes',
      '• Routing: email + Slack/webhook (MVP) → SMS/WhatsApp (later) + in-portal notifications',
      '• Workflow: acknowledge → assign → resolve; maintenance notes + photos; audit log on all changes',
      '• Thresholds: configurable per tenant/site (e.g., offline after 30/60/120 min; low battery at 20%)',
      '',
      '10.14. Finance (Master Admin) — Revenue + Expenses + Profitability',
      'Reference mock: Flowly — Financial Management Dashboard (Dribbble) — use this as the finance layout direction.',
      'Finance goal: track subscriptions + payments from the app, and measure profitability after expenses (enterprise-ready ops).',
      '',
      'Revenue (from app + B2B):',
      '• Subscriptions: active trials, active paid, plan mix, churn, MRR/ARR',
      '• Payments: gross revenue, refunds, failed payments, net revenue',
      '• Conversions: installs → signups → paid conversions (by channel, by country/city)',
      '• Tenant revenue (B2B): revenue per customer/building + growth trends',
      '',
      'Expenses (must-have):',
      '• Cloud infra: DB (Timescale), compute, storage, CDN, logs/monitoring, backups',
      '• IoT vendors: LoRaWAN NS (LORIOT or other), connectivity/VPC add-ons, webhook/ingestion services',
      '• Maps & routing: Mapbox/Google usage costs (tiles, directions, geocoding)',
      '• Messaging: SMS/WhatsApp/email providers (OTP, alerts, receipts)',
      '• Support & ops: customer support tooling, incident management, on-call costs (internal or outsourced)',
      '• Hardware ops: sensor replacements, batteries, installations, truck rolls, spare parts inventory',
      '• Payments fees: Stripe fees, chargebacks, refunds',
      '• Marketing: CAC by channel (later), partner commissions',
      '',
      'Profitability & unit economics:',
      '• Gross margin and net margin',
      '• Cost per active user, cost per tenant, cost per sensor/month',
      '• “Top expensive tenants/sites” (cost drivers: downtime, events volume, map usage, support tickets)',
      '',
      'Exports:',
      '• CSV exports + scheduled monthly finance reports (email) + downloadable invoices/receipts (later)',
      '',
      '10.15. Missing / Recommended (to be enterprise-ready, not just “pretty dashboards”)',
      'These items are usually what separates prototypes from enterprise ops portals:',
      '• Maintenance & Ticketing: incidents → work orders, assign technician, SLA timers, parts used, closure notes/photos',
      '• Installation workflow: “new sensor install” checklist (scan QR/devEUI → bind to bay → baseline readings → validate)',
      '• Configuration management: decoder versions, rules/thresholds per tenant/site, staged rollout + rollback',
      '• Data governance: immutable event log, retention policies, GDPR-style deletes (user data), and export compliance',
      '• Integrations hub: webhook destinations, API keys, partner integrations (payments/operator APIs), and per-tenant toggles',
      '• Notifications center: templates, routing rules, escalation (after X min offline → call/SMS), quiet hours',
      '• SSO for enterprise customers: SAML/OIDC + optional SCIM provisioning (later but plan now)',
      '• Audit + change history everywhere: who changed bay bindings, rules, thresholds, tenant settings',
      '• Backup/restore + disaster readiness: DB backups, replay from raw events, and “rebuild state” tooling',
      '• Performance/scale hygiene: time-range defaults, downsampling, caching, and “fast mode” for large tenants',
    ],
  },
  {
    id: 'action-plan',
    title: '11. Action Plan (Build Order + Deliverables)',
    content: [
      '11.1. Phase A — Foundation (multi-tenant + data model) [Week 1]',
      'Principle: ship a working operator portal early using simulated data, then swap in real LoRaWAN uplinks when gateways arrive.',
      '• ✅ Add tenant model: tenants, memberships, roles (MASTER_ADMIN, CUSTOMER_ADMIN, CUSTOMER_OPS, CUSTOMER_ANALYST)',
      '• ✅ Add core entities: sites, zones, bays, sensors, gateways, weather_stations (or sensor subtype)',
      '• ✅ Add timeseries: sensor_events hypertable (Timescale) + indexes for time + tenant/site',
      '• ✅ Enforce tenant isolation server-side on every query (never rely on UI filtering)',
      '• ✅ Audit log table: record admin/operator changes (bindings, thresholds, overrides, users)',
      '',
      '11.2. Phase B — Simulated Data Ingestion (gateway not required) [Week 1–2]',
      '• ✅ Build /api/replay/upload: upload JSON/CSV “uplink logs” → validate → stage in DB + dead-letter invalid rows',
      '• ✅ Build /api/replay/run: replay staged events into sensor_events in small batches (serverless-safe) with progress tracking',
      '• ✅ Build decoder bench: paste payload → decode preview → save event',
      '• ✅ Add dead-letter view for invalid payloads/decoding failures',
      '',
      '11.3. Phase C — Operator Portal MVP (customer view) [Week 2–3]',
      '• ✅ /portal dashboard: KPI cards + trends + alerts summary (tenant-scoped)',
      '• ✅ /portal/map: live bay colors (Green/Red/Gray) + last update + confidence',
      '• ✅ /portal/sensors: list + details page (health + events + maintenance notes)',
      '• ✅ /portal/events: timeseries viewer with filters + export (CSV)',
      '• ✅ /portal/admin: user management (customer admin) + tenant settings (thresholds)',
      '• Map rendering (Portal): Mapbox GL JS with bay polygons/markers + clustering + layer toggles (bays/sensors/zones)',
      '',
      '11.4. Phase D — Hardware Health + Alerts System [Week 3–4]',
      '• Implement health score + days-in-use + battery drain + signal quality (RSSI/SNR)',
      '• Alerts pipeline: generate alerts (offline, low battery, poor signal, flapping, decode errors)',
      '• Alerts UI: queue + acknowledge/assign/resolve + SLA timers + audit trail',
      '',
      '11.5. Phase E — Master Admin Portal (global view + drilldown) [Week 4–5]',
      '• Global map: all sites, status clusters, filters (tenant/city/health)',
      '• Cross-tenant KPIs: sensors online/offline, events/min, top failing sites/sensors',
      '• Drilldown: tenant → site → zone → bay → sensor (same customer UI, enhanced)',
      '• /portal/admin/tenants: create/disable tenants, manage customer admins',
      '',
      '11.6. Phase F — Analytics/Reporting (hardware + occupancy) [Week 5–6]',
      '• Sensor performance reports (rankings + trends + period comparisons)',
      '• Gateway units overview + coverage panels',
      '• Network overview graph (nodes + edges) + map pinning (optional, after MVP)',
      '• Exports + scheduled reports (weekly/monthly)',
      '',
      '11.6.1. Maps & Navigation (App + Portal)',
      'Recommendation (default): Mapbox for custom bay overlays + styling; use native navigation for the driving experience.',
      '• Portal maps: Mapbox GL JS (web) to render bay polygons + live colors + clustering',
      '• App maps: Mapbox Maps SDK for React Native (Expo compatible via config plugin) for bay overlays + offline styles',
      '• Navigation: Apple Maps / Google Maps deep links for “real navigation” immediately; in-app turn-by-turn later',
      'Viable alternative: Google Maps Platform (Maps SDK + Directions/Traffic) if we prioritize routing accuracy and traffic above custom styling.',
      '',
      '11.7. Phase G — Finance (Master Admin) [Week 6+]',
      '• Integrate app billing metrics (subscriptions, payments, churn, MRR/ARR) via Stripe',
      '• Add expenses tracking (cloud + vendors + hardware ops) → net margin + unit economics',
      '',
      '11.8. Phase H — Swap Simulation → Real LoRaWAN [When gateway arrives]',
      '• Implement /api/iot/uplink webhook + decoder pipeline + validation',
      '• Keep replay tools for demos, QA, and disaster recovery (rebuild state from raw events)',
    ],
  },
]

function computeActionPlanProgress(lines: string[]) {
  // Count actionable items as lines starting with "•"
  // Mark completed items as:
  // - "• ✅ ..."
  // - "• [x] ..."
  // - "• [X] ..."
  const total = lines.filter((l) => l.trim().startsWith('•')).length
  const done = lines.filter((l) => {
    const t = l.trim()
    if (!t.startsWith('•')) return false
    return /^•\s*(✅|\[x\]|\[X\])\s*/.test(t)
  }).length
  const pct = total > 0 ? Math.round((done / total) * 100) : 0
  return { total, done, pct }
}

function CollapsibleNote({ section, isOpen, onToggle }: { section: NoteSection; isOpen: boolean; onToggle: () => void }) {
  return (
    <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between hover:bg-gray-50 transition-colors"
      >
        <h3 className="text-base sm:text-lg font-semibold text-gray-900 text-left">{section.title}</h3>
        {isOpen ? (
          <ChevronDown className="h-5 w-5 text-gray-500 flex-shrink-0" />
        ) : (
          <ChevronRight className="h-5 w-5 text-gray-500 flex-shrink-0" />
        )}
      </button>
      {isOpen && (
        <div className="px-4 sm:px-6 pb-4 sm:pb-6 pt-2">
          <div className="space-y-2 text-sm sm:text-base text-gray-700">
            {section.id === 'action-plan' && (() => {
              const { done, total, pct } = computeActionPlanProgress(section.content)
              return (
                <div className="mb-3">
                  <div className="flex items-center justify-between text-xs sm:text-sm text-gray-600">
                    <span className="font-medium">Progress</span>
                    <span>
                      {pct}% ({done}/{total})
                    </span>
                  </div>
                  <div className="mt-1 h-2 w-full rounded-full bg-gray-200 overflow-hidden">
                    <div className="h-full bg-green-600" style={{ width: `${pct}%` }} />
                  </div>
                  <p className="mt-2 text-xs sm:text-sm text-gray-500">
                    Mark completed items as <span className="font-mono">• ✅</span> or <span className="font-mono">• [x]</span>.
                  </p>
                </div>
              )
            })()}
            {section.content.map((line, idx) => (
              <p key={idx} className={line === '' ? 'h-2' : line.startsWith('•') ? 'ml-2 sm:ml-4' : ''}>
                {line}
              </p>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

export default function NotesPage() {
  const [openSections, setOpenSections] = useState<string[]>(['executive'])

  const toggleSection = (id: string) => {
    setOpenSections((prev) =>
      prev.includes(id) ? prev.filter((sId) => sId !== id) : [...prev, id]
    )
  }

  return (
    <div className="pt-20 sm:pt-24 pb-8 sm:pb-12">
      <Section background="white">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-6 sm:mb-8">
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-gray-900 mb-2 sm:mb-3">
              Technical Notes
            </h1>
            <p className="text-sm sm:text-base text-gray-600">
              Master Technical Specification: ParkSense (UAE Ecosystem)
            </p>
            <p className="text-xs sm:text-sm text-gray-500 mt-1">
              Version: 3.1 | Date: December 19, 2025
            </p>
            <p className="text-xs sm:text-sm text-gray-500">
              Scope: Smart Parking, Hyper-Local Weather, Lifestyle Services & Residential Management
            </p>
          </div>

          <div className="space-y-3 sm:space-y-4">
            {noteSections.map((section) => (
              <CollapsibleNote
                key={section.id}
                section={section}
                isOpen={openSections.includes(section.id)}
                onToggle={() => toggleSection(section.id)}
              />
            ))}
          </div>
        </div>
      </Section>
    </div>
  )
}


