export type ClinicLocale = 'en' | 'ru'

export const CLINIC_LOCALE_STORAGE = 'visiondrive-clinic-locale'

const table = {
  en: {
    practiceConsole: 'Practice console',
    dashboard: 'Dashboard',
    patients: 'Patients',
    procedures: 'Procedures',
    appointments: 'Appointments',
    finance: 'Finance',
    availability: 'Availability',
    reminders: 'Reminders',
    publicBookingLink: 'Booking link',
    publicBookingOn: 'Booking on',
    publicBookingOff: 'Booking off',
    knowledgeBase: 'Knowledge base',
    account: 'Account',
    signOut: 'Sign out',
    loading: 'Loading…',
    retry: 'Retry',
    networkError: 'Connection problem. Check your network and try again.',
    unauthorized: 'Session expired. Sign in again.',
    searchPatients: 'Search patients…',
    searchPatientsHint:
      'Search by name, phone, or email — quick access when someone returns.',
    noPatients: 'No patients yet. Add your first patient to get started.',
    noMatches: 'No matches. Try another spelling or add a new patient.',
    addPatient: 'Add patient',
    sortBy: 'Sort',
    sortNameAsc: 'Name A–Z',
    sortNameDesc: 'Name Z–A',
    sortNewest: 'Newest first',
    thisWeek: 'This week',
    weekOf: 'Week of',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    newAppointment: 'New appointment',
    noAppointmentsWeek: 'No appointments this week.',
    tapDayToAdd: 'Use New appointment or pick another week.',
    editAppointment: 'Edit',
    appointmentStatus: 'Status',
    save: 'Save',
    cancel: 'Cancel',
    today: 'Today',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    localeEn: 'English',
    localeRu: 'Русский',
    language: 'Language',
    timelineAll: 'All',
    timelineAppointments: 'Appointments',
    timelineVisits: 'Visits',
    timelinePayments: 'Payments',
    timelineCrm: 'CRM',
    noTimeline: 'No items for this filter.',
    noHistory: 'No history yet.',
    whatNext: 'What to do next',
    photosBeforeAfter: 'Before / after photos',
    overview: 'Overview',
    timeline: 'Timeline',
    photos: 'Photos',
    payments: 'Payments',
    crm: 'CRM',
    scheduled: 'Scheduled:',
    fromLastVisit: 'From last visit:',
    staffNotesLabel: 'Staff notes:',
    noUpcoming: 'No upcoming appointment or follow-up notes on file.',
    backPatients: '← Patients',
    failedToLoad: 'Failed to load',
    saveFailed: 'Save failed',
    invalidDateTime: 'Invalid date/time',
    notFound: 'Not found',
    operationFailed: 'Failed',
    serverErrorWithCode: 'Server error ({code}). Check the terminal logs.',
    savingEllipsis: 'Saving…',
    updatingEllipsis: 'Updating…',
    uploadingEllipsis: 'Uploading…',
    dashboardIntro: 'Overview for your practice. Data is scoped to your organization only.',
    appointmentsToday: 'Appointments today',
    upcomingScheduled: 'Upcoming scheduled',
    quickActions: 'Quick actions',
    docsFooter: 'Documentation: docs/clinic/ in the VisionDrive repo.',
    backDashboard: '← Dashboard',
    yourAccount: 'Your account',
    signedInAs: 'Signed in as',
    practiceLabel: 'Practice:',
    profileUpdated: 'Profile updated',
    passwordUpdated: 'Password updated',
    couldNotUpdatePassword: 'Could not update password',
    profileHeading: 'Profile',
    displayName: 'Display name',
    saveProfileBtn: 'Save profile',
    changePassword: 'Change password',
    passwordChangeHint:
      'Use a strong password. You will stay signed in on this device after changing it.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    togglePasswordVisibility: 'Toggle password visibility',
    updatePasswordBtn: 'Update password',
    appointmentDefault: 'Appointment',
    dobLabel: 'DOB',
    ageYears: 'years',
    contact: 'Contact',
    close: 'Close',
    edit: 'Edit',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    emptyValue: '—',
    firstName: 'First name',
    lastName: 'Last name',
    middleName: 'Middle name',
    dateOfBirth: 'Date of birth',
    internalNotesStaff: 'Internal notes (staff)',
    internalNotesStaffOnly: 'Internal notes (staff only)',
    anamnesisHeading: 'Medical history (anamnesis)',
    anamnesisHint:
      'Intake and background for clinical staff. Can support patient-safe exports later.',
    anamnesisAllergies: 'Allergies',
    anamnesisMedications: 'Medications',
    anamnesisConditions: 'Conditions / past medical history',
    anamnesisSocial: 'Social history',
    anamnesisNoneOnFile: 'No structured history on file yet.',
    downloadPatientSummaryPdf: 'Patient summary (PDF)',
    patientSummaryPdfHint:
      'Patient-safe export: no internal notes, payments, photos, or clinical visit text.',
    savePatient: 'Save patient',
    logVisit: 'Log a visit',
    logVisitHint:
      'Record what was done today and what follows. Attach before/after photos in the Photos tab.',
    visitDateTime: 'Visit date & time',
    chiefComplaint: 'Chief complaint',
    procedureSummary: 'Procedure / summary',
    nextStepsHint: 'Next steps (shows in “What to do next”)',
    staffNotesVisit: 'Staff notes (visit)',
    saveVisit: 'Save visit',
    recentAppointments: 'Recent appointments',
    noAppointmentsYet: 'No appointments yet.',
    couldNotLogVisit: 'Could not log visit',
    addPhotoTitle: 'Add photo (before / after)',
    addPhotoHint: 'On iPad, use the camera. Link to a visit if you logged one today.',
    linkToVisit: 'Link to visit',
    notLinked: 'Not linked',
    photoType: 'Type',
    photoKindBefore: 'Before',
    photoKindAfter: 'After',
    photoKindOther: 'Other',
    tapToChoosePhoto: 'Tap to take or choose photo',
    visitUnassigned: 'Unassigned',
    noPhotosYet: 'No photos yet for this patient.',
    uploadFailed: 'Upload failed',
    enterValidAmount: 'Enter a valid amount',
    recordPayment: 'Record payment',
    amountAed: 'Amount (AED)',
    amountPlaceholder: 'e.g. 450',
    paymentMethod: 'Method',
    payMethodCard: 'Card',
    payMethodCash: 'Cash',
    payMethodTransfer: 'Transfer',
    payMethodPos: 'POS',
    payMethodOther: 'Other',
    paymentStatusLabel: 'Status',
    payStatusPaid: 'Paid',
    payStatusPending: 'Pending',
    payStatusRefunded: 'Refunded',
    payStatusVoid: 'Void',
    linkToVisitOptional: 'Link to visit (optional)',
    note: 'Note',
    addPayment: 'Add payment',
    noPaymentsRecorded: 'No payments recorded.',
    logInteraction: 'Log interaction',
    crmTypeLabel: 'Type',
    crmDetails: 'Details',
    crmDetailsPlaceholder: 'What was discussed, next touchpoint, preferences…',
    saveToCrm: 'Save to CRM',
    noCrmHistory: 'No CRM history yet.',
    crmTypeNote: 'Note',
    crmTypeCall: 'Call',
    crmTypeWhatsapp: 'WhatsApp',
    crmTypeEmail: 'Email',
    crmTypeFollowUp: 'Follow-up',
    crmTypeOther: 'Other',
    proceduresCatalogSubtitle: 'Catalog · alphabetical',
    addProcedure: 'Add procedure',
    procedureColName: 'Name',
    procedureColDuration: 'Duration',
    procedureColPrice: 'Base price',
    procedureColStatus: 'Status',
    minutesAbbr: 'min',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    noProceduresEmpty: 'No procedures yet. Add your service catalog.',
    newPatientTitle: 'New patient',
    createPatient: 'Create patient',
    newProcedureTitle: 'New procedure',
    procedureName: 'Name',
    durationMinutes: 'Duration (minutes)',
    procedureBufferAfter: 'Buffer after appointment (minutes)',
    procedureBufferAfterHint:
      'Hidden cleanup, prep, travel, or rest time. Clients see only the service duration.',
    basePrice: 'Base price',
    priceHintCents: 'Enter amount in {currency} (stored as cents internally).',
    currency: 'Currency',
    createProcedure: 'Create procedure',
    addPatientFirst: 'Add a patient first.',
    patientLabel: 'Patient',
    selectPlaceholder: 'Select…',
    procedureOptional: 'Procedure (optional)',
    startsAt: 'Starts at',
    titleIfNoProcedure: 'Title (if no procedure)',
    createAppointment: 'Create appointment',
    appointmentStatusScheduled: 'Scheduled',
    appointmentStatusConfirmed: 'Confirmed',
    appointmentStatusArrived: 'Arrived',
    appointmentStatusCompleted: 'Completed',
    appointmentStatusCancelled: 'Cancelled',
    appointmentStatusNoShow: 'No-show',
    appointmentBuffer: 'Buffer',
    appointmentConflict: 'This time conflicts with another appointment.',
    appointmentConflictWith: 'Conflict with {name} at {time}.',
    appointmentConflictBlocked: 'This time overlaps blocked time: {reason}.',
    appointmentConflictWorkingHours: 'This time is outside working hours.',
    appointmentConflictLeadTime: 'This time is inside the minimum lead time ({minutes} min).',
    appointmentAllowOverride: 'Allow scheduling override',
    appointmentOverrideReason: 'Override reason',
    appointmentOverrideReasonHint: 'Explain why this booking should be allowed.',
    appointmentOverrideRequired: 'Tick override and add a reason to book anyway.',
    openAppointment: 'Open appointment',
    viewDay: 'Day',
    dayAgenda: 'Day agenda',
    activeOnly: 'Active only',
    showAll: 'Show all',
    quickStatus: 'Quick status',
    confirmAppointment: 'Confirm',
    markArrived: 'Arrived',
    markCompleted: 'Complete',
    markNoShow: 'No-show',
    startVisit: 'Start visit',
    completeVisit: 'Complete visit',
    createFollowUp: 'Create follow-up',
    reminder: 'Reminder',
    whatsappReminder: 'WhatsApp reminder',
    scheduleReminder24h: 'Schedule 24h reminder',
    noShowFollowUp: 'No-show follow-up',
    copyReminder: 'Copy reminder',
    reminderSent: 'Reminder sent',
    appointmentHistory: 'Appointment history',
    paymentSnapshot: 'Payment',
    visitSnapshot: 'Visit',
    patientContext: 'Patient context',
    noAppointmentEvents: 'No history yet.',
    technicalBreak: 'Technical break',
    occupiedUntil: 'Occupied until',
    unpaid: 'Unpaid',
    paid: 'Paid',
    due: 'Due',
    viewPatientChart: 'Patient chart',
    viewWeek: 'Week',
    viewMonth: 'Month',
    thisMonth: 'This month',
    ariaDropReschedule: 'Drop appointment here to reschedule',
    rescheduleFailed: 'Could not reschedule. Try again or edit the appointment.',
    moreAppointments: '+{count} more',
    prevMonth: 'Previous month',
    nextMonth: 'Next month',
    practiceOsTitle: 'Practice OS',
    practiceOsBrand: 'VisionDrive',
    inventory: 'Inventory',
    inventorySubtitle: 'Stock · movements · low-stock alerts',
    lowStock: 'Low stock',
    lowStockOnly: 'Low stock only',
    lowStockAlerts: 'Low stock alerts',
    revenue: 'Revenue',
    expenses: 'Expenses',
    profit: 'Profit',
    profitability: 'Profitability',
    financeSubtitle: 'Revenue · expenses · profitability',
    financeThisMonth: 'This month',
    financeLast30Days: 'Last 30 days',
    financeNetRevenue: 'Net revenue',
    financePaidRevenue: 'Paid revenue',
    financeRefunds: 'Refunds',
    financePending: 'Pending',
    financeMargin: 'Margin',
    financeAddExpense: 'Add expense',
    financeExpenseCategory: 'Category',
    financeExpenseVendor: 'Vendor',
    financeExpenseDescription: 'Description',
    financeExpenseAmount: 'Amount (AED)',
    financeExpenseDate: 'Expense date',
    financeRecentExpenses: 'Recent expenses',
    financeNoExpenses: 'No expenses in this period.',
    financeCategoryCLOUD: 'Cloud',
    financeCategoryHARDWARE: 'Hardware',
    financeCategoryOPS: 'Operations',
    financeCategorySUPPORT: 'Support',
    financeCategoryMARKETING: 'Marketing',
    financeCategorySOFTWARE: 'Software',
    financeCategoryOTHER: 'Other',
    stockItemName: 'Item name',
    stockSku: 'SKU / code',
    stockUnit: 'Unit',
    stockReorderPoint: 'Reorder alert at',
    stockReorderHint: 'Flag when on-hand is at or below this level (0 = no alert).',
    stockInitialQty: 'Initial quantity',
    stockInitialHint: 'Creates an opening receipt in the movement log.',
    stockNotes: 'Notes',
    stockLinkProcedure: 'Typical procedure (optional)',
    addStockItem: 'Add stock item',
    newStockItemTitle: 'New stock item',
    stockOnHand: 'On hand',
    stockMovements: 'Movements',
    recordMovement: 'Record movement',
    movementType: 'Type',
    movementReceipt: 'Receipt',
    movementAdjustment: 'Adjustment',
    movementConsumption: 'Consumption',
    movementReturn: 'Return',
    quantityDelta: 'Quantity change',
    quantityDeltaHint: 'Positive adds; negative removes. Cannot go below zero.',
    movementNote: 'Note',
    movementReference: 'Reference (e.g. PO)',
    stockItemDetail: 'Stock item',
    saveStockItem: 'Save item',
    noStockItems: 'No stock items yet. Add consumables or retail units.',
    stockInactive: 'Inactive',
    showInactiveStock: 'Show inactive',
    stockLastMovements: 'Recent movements',
    noMovementsYet: 'No movements yet.',
    appointmentsCalendarHint:
      'Drag a card to another day, or tap Move to pick a date (best on iPad).',
    rescheduleMove: 'Move',
    rescheduleSheetTitle: 'Reschedule appointment',
    rescheduleNewDate: 'New date',
    rescheduleApply: 'Apply new date',
    rescheduleHint: 'The time of day stays the same; only the calendar day changes.',
    purchaseOrders: 'Purchase orders',
    purchaseOrdersSubtitle: 'Order from suppliers · receive into stock',
    newPurchaseOrder: 'New purchase order',
    backToPurchaseOrders: '← Purchase orders',
    poSupplier: 'Supplier',
    poReference: 'Reference / PO #',
    poExpectedAt: 'Expected delivery',
    poNotes: 'Notes',
    poLines: 'Lines',
    poAddLine: 'Add line',
    poStockItem: 'Stock item',
    poQtyOrdered: 'Qty ordered',
    poUnitCostOptional: 'Unit cost (cents, optional)',
    poStatusDraft: 'Draft',
    poStatusOrdered: 'Ordered',
    poStatusPartial: 'Partially received',
    poStatusReceived: 'Received',
    poStatusCancelled: 'Cancelled',
    poMarkOrdered: 'Mark ordered',
    poReceiveStock: 'Receive stock',
    poReceiptNote: 'Receipt note (optional)',
    poReceiveQty: 'Qty to receive now',
    poReceivedProgress: 'Received',
    poNoOrders: 'No purchase orders yet.',
    poDetailTitle: 'Purchase order',
    barcodeLabel: 'Barcode',
    barcodeHint: 'Optional. Scannable code (distinct from SKU).',
    consumePerVisitLabel: 'Deduct per completed visit',
    consumePerVisitHint:
      'When a visit is completed for an appointment with the linked procedure, this quantity is removed from stock (if enough on hand).',
    scanBarcode: 'Scan',
    scanningBarcode: 'Scanning…',
    scanNotSupported: 'Camera barcode scanning is not supported in this browser.',
    scanPermissionDenied: 'Camera permission was denied.',
    scanLookupPlaceholder: 'Lookup barcode / SKU…',
    stockLookupSubmit: 'Open item',
    pushNotificationsHeading: 'Low-stock push alerts',
    pushNotificationsHint:
      'Get a browser notification when an item hits its reorder level (requires VAPID keys on the server).',
    pushEnable: 'Enable notifications',
    pushDisable: 'Disable notifications',
    pushNotConfigured: 'Push is not configured for this deployment.',
    pushSubscribed: 'You are subscribed to low-stock alerts on this device.',
    pushSubscribeFailed: 'Could not enable notifications. Check browser settings.',
    inventoryProcedureCol: 'Procedure',
  },
  ar: {
    practiceConsole: 'لوحة الممارسة',
    dashboard: 'لوحة التحكم',
    patients: 'المرضى',
    procedures: 'الإجراءات',
    appointments: 'المواعيد',
    account: 'الحساب',
    signOut: 'تسجيل الخروج',
    loading: 'جاري التحميل…',
    retry: 'إعادة المحاولة',
    networkError: 'مشكلة في الاتصال. تحقق من الشبكة وحاول مرة أخرى.',
    unauthorized: 'انتهت الجلسة. سجّل الدخول من جديد.',
    searchPatients: 'البحث عن مرضى…',
    searchPatientsHint: 'ابحث بالاسم أو الهاتف أو البريد — وصول سريع عند عودة المريض.',
    noPatients: 'لا يوجد مرضى بعد. أضف أول مريض للبدء.',
    noMatches: 'لا نتائج. جرّب كتابة أخرى أو أضف مريضاً جديداً.',
    addPatient: 'إضافة مريض',
    sortBy: 'الترتيب',
    sortNameAsc: 'الاسم أ–ي',
    sortNameDesc: 'الاسم ي–أ',
    sortNewest: 'الأحدث أولاً',
    thisWeek: 'هذا الأسبوع',
    weekOf: 'أسبوع',
    prevWeek: 'الأسبوع السابق',
    nextWeek: 'الأسبوع التالي',
    newAppointment: 'موعد جديد',
    noAppointmentsWeek: 'لا مواعيد هذا الأسبوع.',
    tapDayToAdd: 'استخدم «موعد جديد» أو اختر أسبوعاً آخر.',
    editAppointment: 'تعديل',
    appointmentStatus: 'الحالة',
    save: 'حفظ',
    cancel: 'إلغاء',
    today: 'اليوم',
    mon: 'الإثنين',
    tue: 'الثلاثاء',
    wed: 'الأربعاء',
    thu: 'الخميس',
    fri: 'الجمعة',
    sat: 'السبت',
    sun: 'الأحد',
    localeEn: 'English',
    localeAr: 'العربية',
    language: 'اللغة',
    timelineAll: 'الكل',
    timelineAppointments: 'المواعيد',
    timelineVisits: 'الزيارات',
    timelinePayments: 'المدفوعات',
    timelineCrm: 'التواصل',
    noTimeline: 'لا عناصر لهذا التصفية.',
    noHistory: 'لا يوجد سجل بعد.',
    whatNext: 'ماذا بعد',
    photosBeforeAfter: 'صور قبل / بعد',
    overview: 'نظرة عامة',
    timeline: 'الجدول الزمني',
    photos: 'الصور',
    payments: 'المدفوعات',
    crm: 'العلاقات',
    scheduled: 'مجدول:',
    fromLastVisit: 'من آخر زيارة:',
    staffNotesLabel: 'ملاحظات الفريق:',
    noUpcoming: 'لا موعد قادم ولا ملاحظات متابعة.',
    backPatients: '← المرضى',
    failedToLoad: 'تعذّر التحميل',
    saveFailed: 'فشل الحفظ',
    invalidDateTime: 'تاريخ أو وقت غير صالح',
    notFound: 'غير موجود',
    operationFailed: 'فشلت العملية',
    serverErrorWithCode: 'خطأ في الخادم ({code}). راجع سجلات الطرفية.',
    savingEllipsis: 'جاري الحفظ…',
    updatingEllipsis: 'جاري التحديث…',
    uploadingEllipsis: 'جاري الرفع…',
    dashboardIntro: 'نظرة عامة على ممارستك. البيانات مخصّصة لمؤسستك فقط.',
    appointmentsToday: 'مواعيد اليوم',
    upcomingScheduled: 'المواعيد القادمة',
    quickActions: 'إجراءات سريعة',
    docsFooter: 'التوثيق: مجلد docs/clinic/ في مستودع VisionDrive.',
    backDashboard: '← لوحة التحكم',
    yourAccount: 'حسابك',
    signedInAs: 'مسجّل الدخول كـ',
    practiceLabel: 'الممارسة:',
    profileUpdated: 'تم تحديث الملف',
    passwordUpdated: 'تم تحديث كلمة المرور',
    couldNotUpdatePassword: 'تعذّر تحديث كلمة المرور',
    profileHeading: 'الملف الشخصي',
    displayName: 'الاسم المعروض',
    saveProfileBtn: 'حفظ الملف',
    changePassword: 'تغيير كلمة المرور',
    passwordChangeHint:
      'استخدم كلمة مرور قوية. ستبقى مسجّل الدخول على هذا الجهاز بعد التغيير.',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    togglePasswordVisibility: 'إظهار أو إخفاء كلمة المرور',
    updatePasswordBtn: 'تحديث كلمة المرور',
    appointmentDefault: 'موعد',
    dobLabel: 'تاريخ الميلاد',
    ageYears: 'سنة',
    contact: 'جهة الاتصال',
    close: 'إغلاق',
    edit: 'تعديل',
    phoneLabel: 'الهاتف',
    emailLabel: 'البريد',
    emptyValue: '—',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    middleName: 'الاسم الأوسط',
    dateOfBirth: 'تاريخ الميلاد',
    internalNotesStaff: 'ملاحظات داخلية (الفريق)',
    internalNotesStaffOnly: 'ملاحظات داخلية (لفريق العمل فقط)',
    anamnesisHeading: 'التاريخ الطبي (التاريخ المرضي)',
    anamnesisHint:
      'معلومات السّجل للفريق السريري. يمكن دعم تصديرات آمنة للمريض لاحقاً.',
    anamnesisAllergies: 'الحساسية',
    anamnesisMedications: 'الأدوية الحالية',
    anamnesisConditions: 'الأمراض / التاريخ الطبي',
    anamnesisSocial: 'التاريخ الاجتماعي',
    anamnesisNoneOnFile: 'لا يوجد تاريخ منظّم بعد.',
    downloadPatientSummaryPdf: 'ملخص المريض (PDF)',
    patientSummaryPdfHint:
      'تصدير آمن للمريض: بدون ملاحظات داخلية أو مدفوعات أو صور أو نص سريري للزيارات.',
    savePatient: 'حفظ المريض',
    logVisit: 'تسجيل زيارة',
    logVisitHint:
      'سجّل ما تم اليوم والخطوات التالية. أرفق صور قبل/بعد من تبويب الصور.',
    visitDateTime: 'تاريخ ووقت الزيارة',
    chiefComplaint: 'الشكوى الرئيسية',
    procedureSummary: 'الإجراء / الملخص',
    nextStepsHint: 'الخطوات التالية (تظهر في «ماذا بعد»)',
    staffNotesVisit: 'ملاحظات الفريق (الزيارة)',
    saveVisit: 'حفظ الزيارة',
    recentAppointments: 'المواعيد الأخيرة',
    noAppointmentsYet: 'لا مواعيد بعد.',
    couldNotLogVisit: 'تعذّر تسجيل الزيارة',
    addPhotoTitle: 'إضافة صورة (قبل / بعد)',
    addPhotoHint: 'على الآيباد استخدم الكاميرا. اربط بزيارة إن سجّلت واحدة اليوم.',
    linkToVisit: 'ربط بزيارة',
    notLinked: 'غير مربوط',
    photoType: 'النوع',
    photoKindBefore: 'قبل',
    photoKindAfter: 'بعد',
    photoKindOther: 'أخرى',
    tapToChoosePhoto: 'اضغط لالتقاط أو اختيار صورة',
    visitUnassigned: 'غير مخصّص',
    noPhotosYet: 'لا صور لهذا المريض بعد.',
    uploadFailed: 'فشل الرفع',
    enterValidAmount: 'أدخل مبلغاً صالحاً',
    recordPayment: 'تسجيل دفعة',
    amountAed: 'المبلغ (درهم)',
    amountPlaceholder: 'مثلاً 450',
    paymentMethod: 'الطريقة',
    payMethodCard: 'بطاقة',
    payMethodCash: 'نقداً',
    payMethodTransfer: 'تحويل',
    payMethodPos: 'نقطة بيع',
    payMethodOther: 'أخرى',
    paymentStatusLabel: 'الحالة',
    payStatusPaid: 'مدفوع',
    payStatusPending: 'معلّق',
    payStatusRefunded: 'مسترد',
    payStatusVoid: 'ملغى',
    linkToVisitOptional: 'ربط بزيارة (اختياري)',
    note: 'ملاحظة',
    addPayment: 'إضافة دفعة',
    noPaymentsRecorded: 'لا مدفوعات مسجّلة.',
    logInteraction: 'تسجيل تفاعل',
    crmTypeLabel: 'النوع',
    crmDetails: 'التفاصيل',
    crmDetailsPlaceholder: 'ما نوقش، نقطة الاتصال التالية، التفضيلات…',
    saveToCrm: 'حفظ في CRM',
    noCrmHistory: 'لا سجل علاقات بعد.',
    crmTypeNote: 'ملاحظة',
    crmTypeCall: 'مكالمة',
    crmTypeWhatsapp: 'واتساب',
    crmTypeEmail: 'بريد',
    crmTypeFollowUp: 'متابعة',
    crmTypeOther: 'أخرى',
    proceduresCatalogSubtitle: 'الكتالوج · أبجدي',
    addProcedure: 'إضافة إجراء',
    procedureColName: 'الاسم',
    procedureColDuration: 'المدة',
    procedureColPrice: 'السعر الأساسي',
    procedureColStatus: 'الحالة',
    minutesAbbr: 'د',
    statusActive: 'نشط',
    statusInactive: 'غير نشط',
    noProceduresEmpty: 'لا إجراءات بعد. أضف كتالوج خدماتك.',
    newPatientTitle: 'مريض جديد',
    createPatient: 'إنشاء مريض',
    newProcedureTitle: 'إجراء جديد',
    procedureName: 'الاسم',
    durationMinutes: 'المدة (بالدقائق)',
    basePrice: 'السعر الأساسي',
    priceHintCents: 'أدخل المبلغ بـ {currency} (يُخزَّن بالفلس داخلياً).',
    currency: 'العملة',
    createProcedure: 'إنشاء إجراء',
    addPatientFirst: 'أضف مريضاً أولاً.',
    patientLabel: 'المريض',
    selectPlaceholder: 'اختر…',
    procedureOptional: 'الإجراء (اختياري)',
    startsAt: 'يبدأ في',
    titleIfNoProcedure: 'العنوان (إن لم يُختر إجراء)',
    createAppointment: 'إنشاء موعد',
    appointmentStatusScheduled: 'مجدول',
    appointmentStatusCompleted: 'مكتمل',
    appointmentStatusCancelled: 'ملغى',
    appointmentStatusNoShow: 'لم يحضر',
    viewPatientChart: 'سجل المريض',
    viewWeek: 'أسبوع',
    viewMonth: 'شهر',
    thisMonth: 'هذا الشهر',
    ariaDropReschedule: 'أفلت الموعد هنا لإعادة الجدولة',
    rescheduleFailed: 'تعذّر إعادة الجدولة. حاول مرة أخرى أو عدّل الموعد.',
    moreAppointments: '+{count} أخرى',
    prevMonth: 'الشهر السابق',
    nextMonth: 'الشهر التالي',
    practiceOsTitle: 'نظام الممارسة',
    practiceOsBrand: 'VisionDrive',
    inventory: 'المخزون',
    inventorySubtitle: 'الأصناف · الحركات · تنبيهات النقص',
    lowStock: 'مخزون منخفض',
    lowStockOnly: 'المنخفض فقط',
    lowStockAlerts: 'تنبيهات النقص',
    stockItemName: 'اسم الصنف',
    stockSku: 'رمز / SKU',
    stockUnit: 'الوحدة',
    stockReorderPoint: 'تنبيه عند',
    stockReorderHint: 'يُعلَم عندما يصبح الرصيد ≤ هذا المستوى (0 = بدون تنبيه).',
    stockInitialQty: 'الكمية الافتتاحية',
    stockInitialHint: 'يُنشئ إيصال افتتاح في سجل الحركات.',
    stockNotes: 'ملاحظات',
    stockLinkProcedure: 'إجراء نموذجي (اختياري)',
    addStockItem: 'إضافة صنف',
    newStockItemTitle: 'صنف جديد',
    stockOnHand: 'الرصيد',
    stockMovements: 'الحركات',
    recordMovement: 'تسجيل حركة',
    movementType: 'النوع',
    movementReceipt: 'استلام',
    movementAdjustment: 'تسوية',
    movementConsumption: 'استهلاك',
    movementReturn: 'إرجاع',
    quantityDelta: 'تغيير الكمية',
    quantityDeltaHint: 'الموجب يزيد؛ السالب ينقص. لا يمكن أن يصبح الرصيد سالباً.',
    movementNote: 'ملاحظة',
    movementReference: 'مرجع (مثلاً أمر شراء)',
    stockItemDetail: 'صنف المخزون',
    saveStockItem: 'حفظ الصنف',
    noStockItems: 'لا أصناف بعد. أضف مستهلكات أو وحدات بيع.',
    stockInactive: 'غير نشط',
    showInactiveStock: 'عرض غير النشط',
    stockLastMovements: 'آخر الحركات',
    noMovementsYet: 'لا حركات بعد.',
    appointmentsCalendarHint:
      'اسحب البطاقة إلى يوم آخر، أو اضغط «نقل» لاختيار تاريخ (مناسب للآيباد).',
    rescheduleMove: 'نقل',
    rescheduleSheetTitle: 'إعادة جدولة الموعد',
    rescheduleNewDate: 'تاريخ جديد',
    rescheduleApply: 'تطبيق التاريخ',
    rescheduleHint: 'يبقى وقت اليوم كما هو؛ يتغيّر يوم التقويم فقط.',
    purchaseOrders: 'أوامر الشراء',
    purchaseOrdersSubtitle: 'الطلب من المورّدين · الاستلام إلى المخزون',
    newPurchaseOrder: 'أمر شراء جديد',
    backToPurchaseOrders: '← أوامر الشراء',
    poSupplier: 'المورّد',
    poReference: 'مرجع / رقم أمر الشراء',
    poExpectedAt: 'التسليم المتوقع',
    poNotes: 'ملاحظات',
    poLines: 'البنود',
    poAddLine: 'إضافة بند',
    poStockItem: 'صنف المخزون',
    poQtyOrdered: 'الكمية المطلوبة',
    poUnitCostOptional: 'تكلفة الوحدة (فلس، اختياري)',
    poStatusDraft: 'مسودة',
    poStatusOrdered: 'مُطلَب',
    poStatusPartial: 'مستلم جزئياً',
    poStatusReceived: 'مستلم بالكامل',
    poStatusCancelled: 'ملغى',
    poMarkOrdered: 'تعيين كمطلوب',
    poReceiveStock: 'استلام المخزون',
    poReceiptNote: 'ملاحظة الاستلام (اختياري)',
    poReceiveQty: 'الكمية للاستلام الآن',
    poReceivedProgress: 'المستلم',
    poNoOrders: 'لا أوامر شراء بعد.',
    poDetailTitle: 'أمر شراء',
    barcodeLabel: 'الباركود',
    barcodeHint: 'اختياري. رمز قابل للمسح (مختلف عن SKU).',
    consumePerVisitLabel: 'خصم عند إكمال الزيارة',
    consumePerVisitHint:
      'عند إكمال زيارة لموعد مرتبط بالإجراء المحدد، تُخصم هذه الكمية من المخزون (إن وُجد رصيد كافٍ).',
    scanBarcode: 'مسح',
    scanningBarcode: 'جاري المسح…',
    scanNotSupported: 'مسح الباركود بالكاميرا غير مدعوم في هذا المتصفح.',
    scanPermissionDenied: 'تم رفض إذن الكاميرا.',
    scanLookupPlaceholder: 'بحث باركود / SKU…',
    stockLookupSubmit: 'فتح الصنف',
    pushNotificationsHeading: 'تنبيهات دفع عند نقص المخزون',
    pushNotificationsHint:
      'استلام إشعار في المتصفح عند وصول صنف إلى حد إعادة الطلب (يتطلب مفاتيح VAPID على الخادم).',
    pushEnable: 'تفعيل الإشعارات',
    pushDisable: 'إيقاف الإشعارات',
    pushNotConfigured: 'الدفع غير مهيأ في هذا النشر.',
    pushSubscribed: 'أنت مشترك في تنبيهات النقص على هذا الجهاز.',
    pushSubscribeFailed: 'تعذّر تفعيل الإشعارات. تحقق من إعدادات المتصفح.',
    inventoryProcedureCol: 'الإجراء',
  },
} as const

export type ClinicStringKey = keyof typeof table.en
export type ClinicStrings = Record<ClinicStringKey, string>

const ruOverrides: Partial<ClinicStrings> = {
  practiceConsole: 'Панель клиники',
  dashboard: 'Дашборд',
  patients: 'Пациенты',
  procedures: 'Процедуры',
  appointments: 'Записи',
  finance: 'Финансы',
  availability: 'Доступность',
  reminders: 'Напоминания',
  publicBookingLink: 'Ссылка для записи',
  publicBookingOn: 'Запись включена',
  publicBookingOff: 'Запись выключена',
  knowledgeBase: 'База знаний',
  inventory: 'Склад',
  purchaseOrders: 'Закупки',
  account: 'Аккаунт',
  signOut: 'Выйти',
  loading: 'Загрузка...',
  retry: 'Повторить',
  networkError: 'Проблема с подключением. Проверьте сеть и попробуйте снова.',
  unauthorized: 'Сессия истекла. Войдите снова.',
  addPatient: 'Добавить пациента',
  newAppointment: 'Новая запись',
  today: 'Сегодня',
  mon: 'Пн',
  tue: 'Вт',
  wed: 'Ср',
  thu: 'Чт',
  fri: 'Пт',
  sat: 'Сб',
  sun: 'Вс',
  localeEn: 'English',
  localeRu: 'Русский',
  language: 'Язык',
  timelineAll: 'Все',
  timelineAppointments: 'Записи',
  timelineVisits: 'Визиты',
  timelinePayments: 'Платежи',
  timelineCrm: 'CRM',
  noTimeline: 'Нет элементов для этого фильтра.',
  noHistory: 'Истории пока нет.',
  whatNext: 'Что дальше',
  photosBeforeAfter: 'Фото до / после',
  overview: 'Обзор',
  timeline: 'История',
  photos: 'Фото',
  payments: 'Платежи',
  crm: 'CRM',
  scheduled: 'Запланировано:',
  fromLastVisit: 'После последнего визита:',
  staffNotesLabel: 'Заметки персонала:',
  noUpcoming: 'Нет ближайших записей или заметок по follow-up.',
  backPatients: '<- Пациенты',
  failedToLoad: 'Не удалось загрузить',
  saveFailed: 'Не удалось сохранить',
  invalidDateTime: 'Некорректная дата или время',
  notFound: 'Не найдено',
  operationFailed: 'Операция не выполнена',
  serverErrorWithCode: 'Ошибка сервера ({code}). Проверьте логи терминала.',
  savingEllipsis: 'Сохранение...',
  updatingEllipsis: 'Обновление...',
  uploadingEllipsis: 'Загрузка...',
  dashboardIntro: 'Обзор вашей клиники. Данные доступны только вашей организации.',
  appointmentsToday: 'Записи сегодня',
  upcomingScheduled: 'Ближайшие записи',
  quickActions: 'Быстрые действия',
  docsFooter: 'Документация: docs/clinic/ в репозитории VisionDrive.',
  backDashboard: '<- Дашборд',
  yourAccount: 'Ваш аккаунт',
  signedInAs: 'Вы вошли как',
  practiceLabel: 'Клиника:',
  profileUpdated: 'Профиль обновлён',
  passwordUpdated: 'Пароль обновлён',
  couldNotUpdatePassword: 'Не удалось обновить пароль',
  profileHeading: 'Профиль',
  displayName: 'Имя',
  saveProfileBtn: 'Сохранить профиль',
  changePassword: 'Сменить пароль',
  passwordChangeHint:
    'Используйте надёжный пароль. После смены пароля вы останетесь в системе на этом устройстве.',
  currentPassword: 'Текущий пароль',
  newPassword: 'Новый пароль',
  togglePasswordVisibility: 'Показать или скрыть пароль',
  updatePasswordBtn: 'Обновить пароль',
  appointmentDefault: 'Запись',
  dobLabel: 'Дата рождения',
  ageYears: 'лет',
  contact: 'Контакты',
  close: 'Закрыть',
  edit: 'Редактировать',
  phoneLabel: 'Телефон',
  emailLabel: 'Email',
  emptyValue: '—',
  firstName: 'Имя',
  lastName: 'Фамилия',
  middleName: 'Отчество',
  dateOfBirth: 'Дата рождения',
  internalNotesStaff: 'Внутренние заметки (персонал)',
  internalNotesStaffOnly: 'Внутренние заметки (только персонал)',
  anamnesisHeading: 'Медицинский анамнез',
  anamnesisHint: 'Анкета и фон для клинической команды. Позже можно использовать для безопасного экспорта пациенту.',
  anamnesisAllergies: 'Аллергии',
  anamnesisMedications: 'Лекарства',
  anamnesisConditions: 'Состояния / история болезни',
  anamnesisSocial: 'Социальный анамнез',
  anamnesisNoneOnFile: 'Структурированный анамнез пока не заполнен.',
  downloadPatientSummaryPdf: 'Сводка пациента (PDF)',
  patientSummaryPdfHint:
    'Безопасный экспорт для пациента: без внутренних заметок, платежей, фото и клинического текста визитов.',
  savePatient: 'Сохранить пациента',
  logVisit: 'Записать визит',
  logVisitHint: 'Зафиксируйте, что сделано сегодня и что дальше. Фото до/после добавляются во вкладке Фото.',
  visitDateTime: 'Дата и время визита',
  chiefComplaint: 'Жалоба',
  procedureSummary: 'Процедура / резюме',
  nextStepsHint: 'Следующие шаги (показывается в “Что дальше”)',
  staffNotesVisit: 'Заметки персонала (визит)',
  saveVisit: 'Сохранить визит',
  recentAppointments: 'Недавние записи',
  noAppointmentsYet: 'Записей пока нет.',
  couldNotLogVisit: 'Не удалось записать визит',
  addPhotoTitle: 'Добавить фото (до / после)',
  addPhotoHint: 'На iPad используйте камеру. По возможности привяжите фото к сегодняшнему визиту.',
  linkToVisit: 'Привязать к визиту',
  notLinked: 'Не привязано',
  photoType: 'Тип',
  photoKindBefore: 'До',
  photoKindAfter: 'После',
  photoKindOther: 'Другое',
  tapToChoosePhoto: 'Нажмите, чтобы сделать или выбрать фото',
  visitUnassigned: 'Не назначено',
  noPhotosYet: 'Фото для этого пациента пока нет.',
  uploadFailed: 'Загрузка не удалась',
  enterValidAmount: 'Введите корректную сумму',
  recordPayment: 'Записать оплату',
  amountAed: 'Сумма (AED)',
  amountPlaceholder: 'например, 450',
  paymentMethod: 'Метод',
  payMethodCard: 'Карта',
  payMethodCash: 'Наличные',
  payMethodTransfer: 'Перевод',
  payMethodPos: 'POS',
  payMethodOther: 'Другое',
  paymentStatusLabel: 'Статус',
  payStatusPaid: 'Оплачено',
  payStatusPending: 'Ожидает',
  payStatusRefunded: 'Возврат',
  payStatusVoid: 'Аннулировано',
  linkToVisitOptional: 'Привязать к визиту (опционально)',
  note: 'Заметка',
  addPayment: 'Добавить оплату',
  noPaymentsRecorded: 'Платежей пока нет.',
  logInteraction: 'Записать контакт',
  crmTypeLabel: 'Тип',
  crmDetails: 'Детали',
  crmDetailsPlaceholder: 'Что обсудили, следующий контакт, предпочтения...',
  saveToCrm: 'Сохранить в CRM',
  noCrmHistory: 'Истории CRM пока нет.',
  crmTypeNote: 'Заметка',
  crmTypeCall: 'Звонок',
  crmTypeWhatsapp: 'WhatsApp',
  crmTypeEmail: 'Email',
  crmTypeFollowUp: 'Follow-up',
  crmTypeOther: 'Другое',
  addProcedure: 'Добавить процедуру',
  procedureColName: 'Название',
  procedureColDuration: 'Длительность',
  procedureColPrice: 'Базовая цена',
  procedureColStatus: 'Статус',
  statusActive: 'Активно',
  statusInactive: 'Неактивно',
  newPatientTitle: 'Новый пациент',
  createPatient: 'Создать пациента',
  newProcedureTitle: 'Новая процедура',
  procedureName: 'Название',
  durationMinutes: 'Длительность (минуты)',
  procedureBufferAfter: 'Буфер после записи (минуты)',
  procedureBufferAfterHint:
    'Скрытое время на уборку, подготовку, дорогу или отдых. Клиент видит только длительность услуги.',
  basePrice: 'Базовая цена',
  currency: 'Валюта',
  createProcedure: 'Создать процедуру',
  patientLabel: 'Пациент',
  selectPlaceholder: 'Выберите...',
  procedureOptional: 'Процедура (опционально)',
  startsAt: 'Начало',
  createAppointment: 'Создать запись',
  appointmentStatusScheduled: 'Запланировано',
  appointmentStatusConfirmed: 'Подтверждено',
  appointmentStatusArrived: 'Пришел',
  appointmentStatusCompleted: 'Завершено',
  appointmentStatusCancelled: 'Отменено',
  appointmentStatusNoShow: 'Не явился',
  appointmentBuffer: 'Буфер',
  appointmentConflict: 'Это время пересекается с другой записью.',
  appointmentConflictWith: 'Конфликт с {name} в {time}.',
  appointmentConflictBlocked: 'Это время пересекается с закрытым слотом: {reason}.',
  appointmentConflictWorkingHours: 'Это время вне рабочих часов.',
  appointmentConflictLeadTime: 'Это время внутри минимального окна до записи ({minutes} мин).',
  appointmentAllowOverride: 'Разрешить исключение в расписании',
  appointmentOverrideReason: 'Причина исключения',
  appointmentOverrideReasonHint: 'Объясните, почему эту запись нужно разрешить.',
  appointmentOverrideRequired: 'Включите исключение и добавьте причину, чтобы записать всё равно.',
  openAppointment: 'Открыть запись',
  viewDay: 'День',
  dayAgenda: 'Повестка дня',
  activeOnly: 'Только активные',
  showAll: 'Показать все',
  quickStatus: 'Быстрый статус',
  confirmAppointment: 'Подтвердить',
  markArrived: 'Пришел',
  markCompleted: 'Завершить',
  markNoShow: 'Не явился',
  startVisit: 'Начать визит',
  completeVisit: 'Завершить визит',
  createFollowUp: 'Создать повтор',
  reminder: 'Напоминание',
  whatsappReminder: 'WhatsApp-напоминание',
  scheduleReminder24h: 'Запланировать за 24ч',
  noShowFollowUp: 'Сообщение после неявки',
  copyReminder: 'Скопировать напоминание',
  reminderSent: 'Напоминание отправлено',
  appointmentHistory: 'История записи',
  paymentSnapshot: 'Оплата',
  visitSnapshot: 'Визит',
  patientContext: 'Контекст пациента',
  noAppointmentEvents: 'Истории пока нет.',
  technicalBreak: 'Технический перерыв',
  occupiedUntil: 'Занято до',
  unpaid: 'Не оплачено',
  paid: 'Оплачено',
  due: 'К оплате',
  viewPatientChart: 'Карта пациента',
  viewWeek: 'Неделя',
  viewMonth: 'Месяц',
  thisMonth: 'Этот месяц',
  practiceOsTitle: 'Practice OS',
  practiceOsBrand: 'VisionDrive',
  inventorySubtitle: 'Остатки · движения · уведомления',
  lowStock: 'Мало на складе',
  lowStockOnly: 'Только низкий остаток',
  lowStockAlerts: 'Низкий остаток',
  stockItemName: 'Позиция',
  stockSku: 'SKU / код',
  stockUnit: 'Единица',
  stockReorderPoint: 'Оповещать при',
  addStockItem: 'Добавить позицию',
  newStockItemTitle: 'Новая позиция',
  stockOnHand: 'В наличии',
  stockMovements: 'Движения',
  recordMovement: 'Записать движение',
  movementReceipt: 'Поступление',
  movementAdjustment: 'Коррекция',
  movementConsumption: 'Расход',
  movementReturn: 'Возврат',
  quantityDelta: 'Изменение количества',
  stockItemDetail: 'Позиция склада',
  saveStockItem: 'Сохранить позицию',
  noStockItems: 'Позиций пока нет.',
  showInactiveStock: 'Показать неактивные',
  stockLastMovements: 'Последние движения',
  noMovementsYet: 'Движений пока нет.',
  revenue: 'Выручка',
  expenses: 'Расходы',
  profit: 'Прибыль',
  profitability: 'Рентабельность',
  financeSubtitle: 'Выручка · расходы · прибыльность',
  financeThisMonth: 'Этот месяц',
  financeLast30Days: 'Последние 30 дней',
  financeNetRevenue: 'Чистая выручка',
  financePaidRevenue: 'Оплаченная выручка',
  financeRefunds: 'Возвраты',
  financePending: 'Ожидает оплаты',
  financeMargin: 'Маржа',
  financeAddExpense: 'Добавить расход',
  financeExpenseCategory: 'Категория',
  financeExpenseVendor: 'Поставщик',
  financeExpenseDescription: 'Описание',
  financeExpenseAmount: 'Сумма (AED)',
  financeExpenseDate: 'Дата расхода',
  financeRecentExpenses: 'Последние расходы',
  financeNoExpenses: 'За период расходов нет.',
  financeCategoryCLOUD: 'Облако',
  financeCategoryHARDWARE: 'Оборудование',
  financeCategoryOPS: 'Операционные расходы',
  financeCategorySUPPORT: 'Поддержка',
  financeCategoryMARKETING: 'Маркетинг',
  financeCategorySOFTWARE: 'ПО',
  financeCategoryOTHER: 'Другое',
}

export function clinicStrings(locale: ClinicLocale): ClinicStrings {
  return (locale === 'ru' ? { ...table.en, ...ruOverrides } : table.en) as ClinicStrings
}
