export type ClinicLocale = 'en' | 'ar'

export const CLINIC_LOCALE_STORAGE = 'visiondrive-clinic-locale'

const table = {
  en: {
    practiceConsole: 'Practice console',
    dashboard: 'Dashboard',
    patients: 'Patients',
    procedures: 'Procedures',
    appointments: 'Appointments',
    account: 'Account',
    signOut: 'Sign out',
    loading: 'Loading…',
    retry: 'Retry',
    networkError: 'Connection problem. Check your network and try again.',
    unauthorized: 'Session expired. Sign in again.',
    searchPatients: 'Search patients…',
    searchPatientsHint:
      'Search by name, phone, or email — quick access when someone returns.',
    noPatients: 'No patients yet. Add your first patient to get started.',
    noMatches: 'No matches. Try another spelling or add a new patient.',
    addPatient: 'Add patient',
    sortBy: 'Sort',
    sortNameAsc: 'Name A–Z',
    sortNameDesc: 'Name Z–A',
    sortNewest: 'Newest first',
    thisWeek: 'This week',
    weekOf: 'Week of',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    newAppointment: 'New appointment',
    noAppointmentsWeek: 'No appointments this week.',
    tapDayToAdd: 'Use New appointment or pick another week.',
    editAppointment: 'Edit',
    appointmentStatus: 'Status',
    save: 'Save',
    cancel: 'Cancel',
    today: 'Today',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    localeEn: 'English',
    localeAr: 'العربية',
    language: 'Language',
    timelineAll: 'All',
    timelineAppointments: 'Appointments',
    timelineVisits: 'Visits',
    timelinePayments: 'Payments',
    timelineCrm: 'CRM',
    noTimeline: 'No items for this filter.',
    noHistory: 'No history yet.',
    whatNext: 'What to do next',
    photosBeforeAfter: 'Before / after photos',
    overview: 'Overview',
    timeline: 'Timeline',
    photos: 'Photos',
    payments: 'Payments',
    crm: 'CRM',
    scheduled: 'Scheduled:',
    fromLastVisit: 'From last visit:',
    staffNotesLabel: 'Staff notes:',
    noUpcoming: 'No upcoming appointment or follow-up notes on file.',
    backPatients: '← Patients',
  },
  ar: {
    practiceConsole: 'لوحة الممارسة',
    dashboard: 'لوحة التحكم',
    patients: 'المرضى',
    procedures: 'الإجراءات',
    appointments: 'المواعيد',
    account: 'الحساب',
    signOut: 'تسجيل الخروج',
    loading: 'جاري التحميل…',
    retry: 'إعادة المحاولة',
    networkError: 'مشكلة في الاتصال. تحقق من الشبكة وحاول مرة أخرى.',
    unauthorized: 'انتهت الجلسة. سجّل الدخول من جديد.',
    searchPatients: 'البحث عن مرضى…',
    searchPatientsHint: 'ابحث بالاسم أو الهاتف أو البريد — وصول سريع عند عودة المريض.',
    noPatients: 'لا يوجد مرضى بعد. أضف أول مريض للبدء.',
    noMatches: 'لا نتائج. جرّب كتابة أخرى أو أضف مريضاً جديداً.',
    addPatient: 'إضافة مريض',
    sortBy: 'الترتيب',
    sortNameAsc: 'الاسم أ–ي',
    sortNameDesc: 'الاسم ي–أ',
    sortNewest: 'الأحدث أولاً',
    thisWeek: 'هذا الأسبوع',
    weekOf: 'أسبوع',
    prevWeek: 'الأسبوع السابق',
    nextWeek: 'الأسبوع التالي',
    newAppointment: 'موعد جديد',
    noAppointmentsWeek: 'لا مواعيد هذا الأسبوع.',
    tapDayToAdd: 'استخدم «موعد جديد» أو اختر أسبوعاً آخر.',
    editAppointment: 'تعديل',
    appointmentStatus: 'الحالة',
    save: 'حفظ',
    cancel: 'إلغاء',
    today: 'اليوم',
    mon: 'الإثنين',
    tue: 'الثلاثاء',
    wed: 'الأربعاء',
    thu: 'الخميس',
    fri: 'الجمعة',
    sat: 'السبت',
    sun: 'الأحد',
    localeEn: 'English',
    localeAr: 'العربية',
    language: 'اللغة',
    timelineAll: 'الكل',
    timelineAppointments: 'المواعيد',
    timelineVisits: 'الزيارات',
    timelinePayments: 'المدفوعات',
    timelineCrm: 'التواصل',
    noTimeline: 'لا عناصر لهذا التصفية.',
    noHistory: 'لا يوجد سجل بعد.',
    whatNext: 'ماذا بعد',
    photosBeforeAfter: 'صور قبل / بعد',
    overview: 'نظرة عامة',
    timeline: 'الجدول الزمني',
    photos: 'الصور',
    payments: 'المدفوعات',
    crm: 'العلاقات',
    scheduled: 'مجدول:',
    fromLastVisit: 'من آخر زيارة:',
    staffNotesLabel: 'ملاحظات الفريق:',
    noUpcoming: 'لا موعد قادم ولا ملاحظات متابعة.',
    backPatients: '← المرضى',
  },
} as const

export type ClinicStringKey = keyof typeof table.en
export type ClinicStrings = Record<ClinicStringKey, string>

export function clinicStrings(locale: ClinicLocale): ClinicStrings {
  return (locale === 'ar' ? table.ar : table.en) as ClinicStrings
}
